// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:cdef2f12-b0b2-4e46-af85-ebe1a6796921",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_lqYCOgSod",
    "aws_user_pools_web_client_id": "4gjvmmh1fv1l309td9okl0rdvm"
};


export default awsmobile;
